### ISSUE TITLE
cascading input properties are not supported

### ISSUE THREAD

**Issue by gongdaoqi-ola** [richinsley/comfy2go#2]
node: VHS_VideoCombine
required_inputs:
"format": [
[
"image/gif",
"image/webp",
"video/16bit-png",
"video/ProRes",
[
"video/av1-webm",
[
[
"pix_fmt",
[
"yuv420p10le",
"yuv420p"
]
],
[
"crf",
"INT",
{
"default": 23,
"min": 0,
"max": 100,
"step": 1
}
],
[
"input_color_depth",
[
"8bit",
"16bit"
]
],
[
"save_metadata",
"BOOLEAN",
{
"default": true
}
]
]
],
[
"video/h264-mp4",
[
[
"pix_fmt",
[
"yuv420p10le",
"yuv420p"
]
],
[
"crf",
"INT",
{
"default": 19,
"min": 0,
"max": 100,
"step": 1
}
],
[
"save_metadata",
"BOOLEAN",
{
"default": true
}
]
]
],
the param "pix_fmt/crf/save_metadata" is changed by param "format"
"pix_fmt/crf/save_metadata" is not required by node, but is required by special format node, now is unsupported

{"VHS_VideoCombine": {"input": {"required": {"images": ["IMAGE"], "frame_rate": ["INT", {"default": 8, "min": 1, "step": 1}], "loop_count": ["INT", {"default": 0, "min": 0, "max": 100, "step": 1}], "filename_prefix": ["STRING", {"default": "AnimateDiff"}], "format": [["image/gif", "image/webp", "video/16bit-png", "video/ProRes", ["video/av1-webm", [["pix_fmt", ["yuv420p10le", "yuv420p"]], ["crf", "INT", {"default": 23, "min": 0, "max": 100, "step": 1}], ["input_color_depth", ["8bit", "16bit"]], ["save_metadata", "BOOLEAN", {"default": true}]]], ["video/h264-mp4", [["pix_fmt", ["yuv420p10le", "yuv420p"]], ["crf", "INT", {"default": 19, "min": 0, "max": 100, "step": 1}], ["save_metadata", "BOOLEAN", {"default": true}]]], ["video/h265-mp4", [["pix_fmt", ["yuv420p10le", "yuv420p"]], ["crf", "INT", {"default": 22, "min": 0, "max": 100, "step": 1}], ["save_metadata", "BOOLEAN", {"default": true}]]], ["video/nvenc_h264-mp4", [["pix_fmt", ["yuv420p", "yuv420p10le"]], ["bitrate", "INT", {"default": 10, "min": 1, "max": 999, "step": 1}], ["megabit", "BOOLEAN", {"default": true}], ["save_metadata", "BOOLEAN", {"default": true}]]], ["video/nvenc_hevc-mp4", [["pix_fmt", ["yuv420p", "yuv420p10le"]], ["bitrate", "INT", {"default": 10, "min": 1, "max": 999, "step": 1}], ["megabit", "BOOLEAN", {"default": true}], ["save_metadata", "BOOLEAN", {"default": true}]]], ["video/webm", [["crf", "INT", {"default": 20, "min": 0, "max": 100, "step": 1}], ["save_metadata", "BOOLEAN", {"default": true}]]]]], "pingpong": ["BOOLEAN", {"default": false}], "save_output": ["BOOLEAN", {"default": true}]}, "optional": {"audio": ["VHS_AUDIO"]}, "hidden": {"prompt": "PROMPT", "extra_pnginfo": "EXTRA_PNGINFO", "unique_id": "UNIQUE_ID"}}, "output": ["VHS_FILENAMES"], "output_is_list": [false], "output_name": ["Filenames"], "name": "VHS_VideoCombine", "display_name": "Video Combine \ud83c\udfa5\ud83c\udd65\ud83c\udd57\ud83c\udd62", "description": "", "category": "Video Helper Suite \ud83c\udfa5\ud83c\udd65\ud83c\udd57\ud83c\udd62", "output_node": true}}

**Comment by richinsley** [comment]
fixed in v0.4.0
