### ISSUE TITLE
Returning data with SVD ComfyUI Nodes

### ISSUE THREAD

**Issue by dreamfast** [richinsley/comfy2go#3]
Hi there, thanks for this great plugin.

With the release of SDV ComfyUI has new node types and file formats to consider. I am not the best Go coder, but will try make a PR to allow for this.

For now it seems with this package it only considers images.

A format like mp4 or webp will return the following error: `Deserializing Status Message: json: cannot unmarshal bool into Go struct field .output of type client.DataOutputImages`

[txt2video_1_2.json](https://github.com/richinsley/comfy2go/files/14155627/txt2video_1_2.json) - this is the workflow used, originally found on CivitAI. Just recently StabilityAI released version 1.1 of SDV, so that is the model I am using.

**Comment by dreamfast** [comment]
Trying to output an actual video file, that is not webp format will return `Error loading graph JSON: json: cannot unmarshal object into Go struct field GraphNode.nodes.widgets_values of type []interface {}`

**Comment by richinsley** [comment]
I'm looking into this now.  It looks like the widget properties for the VHS_VideoCombine is defined as a map of properties instead of an array.  I'm not sure if this is a one-off custom implementation by the author or if this is a new style of node serialization defined in ComfyUI.

**Comment by richinsley** [comment]
In v0.4.0, DataOutputImages is changed to DataOutput, which has a dictionary of the output types instead of just the 'images'
