### ISSUE TITLE
Deserializing Status Message: json: cannot unmarshal bool into Go struct field .output of type client.DataOutput

### ISSUE THREAD

**Issue by dreamfast** [richinsley/comfy2go#6]
Thanks for the recent changes, they had made it a bit easier to understand the package and how it works.

I am still facing issues with text2video. This is the workflow I am using at the moment. [txt2vid.json](https://github.com/richinsley/comfy2go/files/14468224/txt2vid.json) it returns a webp format as the final result.

With my previous PR I was able to get ComfyUI generating the request, however the response is returning `Deserializing Status Message: json: cannot unmarshal bool into Go struct field .output of type client.DataOutput` somewhere.

Within `client/dataitems.go` I can see there is the struct `DataOutput` which I thought may be related.

However making the following changes seems to have no affect.

```go
type DataOutput struct {
	Filename  string           `json:"filename"`
	Subfolder string           `json:"subfolder"`
	Type      string           `json:"type"`
	Output    *json.RawMessage `json:"output"`
}
```

```go
type DataOutput struct {
	Filename  string           `json:"filename"`
	Subfolder string           `json:"subfolder"`
	Type      string           `json:"type"`
	Output    *interface{} `json:"output"`
}
```

```go
type DataOutput struct {
	Filename  string           `json:"filename"`
	Subfolder string           `json:"subfolder"`
	Type      string           `json:"type"`
	Output    bool `json:"output"`
}
```

Outside of that I can't see too easily what would be the cause. I am happy to provide any information to help solve it.

**Comment by richinsley** [comment]
This is fixed now in v0.5.0
Also, I added the ability to get/set the value of Note nodes via a "text" property.
